# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: oneclick-core_development
        options: >-
          --health-cmd "pg_isready -U root -d oneclick-core_development"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.6

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg2
        echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
        wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y postgresql-13-postgis-3 libpq-dev

    - name: Install gems
      run: bundle install --jobs 4 --retry 3

    - name: Setup database
      env:
        RAILS_ENV: test
        DATABASE_URL: "postgres://rails_user:password@localhost:5432/test_db"
      run: |
        bundle exec rake db:setup
        psql -U rails_user -d test_db -c "CREATE EXTENSION IF NOT EXISTS postgis;"

    - name: Run tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rake db:migrate
        bundle exec rspec